# 全域配置
project:
  name: "Inazuma Eleven LoRA Factory"
  version: "1.0.0"
  author: "Your Name"

# 路徑配置
paths:
  # 共用資料倉儲路徑
  warehouse_root: "/mnt/c/AI_LLM_projects/ai_warehouse"

  # 專案資料路徑（透過符號連結指向 warehouse）
  data_root: "data/"  # -> warehouse/training_data/inazuma-eleven/
  models_root: "models/"  # -> warehouse/models/lora/character_loras/inazuma-eleven/
  output_root: "outputs/"  # -> warehouse/outputs/inazuma-eleven/

  # Warehouse 中的實際路徑
  warehouse_training_data: "/mnt/c/AI_LLM_projects/ai_warehouse/training_data/inazuma-eleven"
  warehouse_models: "/mnt/c/AI_LLM_projects/ai_warehouse/models/lora/character_loras/inazuma-eleven"
  warehouse_outputs: "/mnt/c/AI_LLM_projects/ai_warehouse/outputs/inazuma-eleven"
  warehouse_cache: "/mnt/c/AI_LLM_projects/ai_warehouse/cache/inazuma-eleven"

  # Base models（共用的 Stable Diffusion 模型）
  base_models_root: "/mnt/c/AI_LLM_projects/ai_warehouse/models/stable-diffusion"

  # 快取和日誌
  cache_root: "/mnt/c/AI_LLM_projects/ai_warehouse/cache/inazuma-eleven/"
  logs_root: "/mnt/c/AI_LLM_projects/ai_warehouse/outputs/inazuma-eleven/logs/"

# 硬體配置
hardware:
  gpu:
    device: "cuda:0"
    vram_gb: 16
    enable_xformers: true  # 記憶體優化

  cpu:
    num_workers: 8  # DataLoader workers
    parallel_processing: true

# 模型配置
models:
  clip:
    model_name: "ViT-L/14"
    device: "cuda"

  tagger:
    model_name: "wd14-vit-v3"
    repo_id: "SmilingWolf/wd-vit-tagger-v3"

  face_detector:
    model_name: "anime-face-detector"
    confidence: 0.7

# 快取策略
caching:
  enable_clip_cache: true
  enable_hash_cache: true
  cache_ttl_days: 30  # 快取有效期
  max_cache_size_gb: 50

# 日誌配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  save_to_file: true
  console_output: true

# 安全設定
safety:
  backup_before_delete: true
  require_confirmation: true
  max_file_size_mb: 500  # 單檔最大大小