# Dataset Configuration for Battle Dataset
# Use with --dataset_config option

[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = 2

[[datasets]]
resolution = [512, 512]
batch_size = 4
enable_bucket = true
min_bucket_reso = 384
max_bucket_reso = 768
bucket_reso_steps = 64
bucket_no_upscale = false

  [[datasets.subsets]]
  image_dir = "/mnt/c/AI_LLM_projects/ai_warehouse/training_data/inazuma-eleven/dataset_battle/12_inazuma_character"
  num_repeats = 1
